language: scala
dist: trusty
sudo: true
group: beta
jdk:
  - oraclejdk8
stages:
  - validations
  - test
  - test-sbt
  - java11
jobs:
  include:
    - stage: validations
      script: framework/bin/validate-code
      name: "Code validations (format, binary compatibilty, whitesource, etc.)"
    - script: framework/bin/validate-docs
      name: "Validate docs (links, sample code, etc.)"
    - script: framework/bin/validate-microbenchmarks
      name: "Validate that microbenchmarks are runnable"
    - stage: validations
      script: framework/bin/publish-local
      name: "Run a publishLocal for the default scala version"
    - stage: test
      script: framework/bin/test-scala-211
      name: "Run tests for Scala 2.11"
    - script: framework/bin/test-scala-212
      name: "Run tests for Scala 2.12"
    - script: framework/bin/test-scala-213
      name: "Run tests for Scala 2.13"
    - script: framework/bin/test-docs
      name: "Run documentation tests"
    - stage: test-sbt
      script: framework/bin/test-sbt-plugins-0_13
      name: "Scripted tests for sbt 0.13"
    - script: framework/bin/test-sbt-plugins-1_0
      name: "Scripted tests for sbt 1"
    # Test against Open JDK 11, but only for Scala 2.12
    - stage: java11
      jdk: openjdk11
      script: framework/bin/test-scala-212
      name: "Run tests for Scala 2.12 and Java 11"

matrix:
  allow_failures:
    # We are not fully validating for Java 11 yet, so we allow this to
    # failure until we tackle all the problems. Anyway, having it at the
    # build helps us to track the progress and discover problems sooner.
    - jdk: openjdk11

env:
  global:
    secure: "NS2hMbBcmi6EF4QxtcNs4A2ZuNmIdLYQRJUWWejgnD4YtcsmoVjxrHRedqrnDdui4DyvaxWhg/3Uds23jEKTSbbh3ZphLO77BVgM2nUGUvVoa4i6qGF2eZFlIhq2G1gM700GPV7X4KmyjYi2HtH8CWBTkqP3g0An63mCZw/Gnlk="

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_cache:
- rm -rf $HOME/.ivy2/local
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
- find $HOME/.sbt -name "*.lock" -delete
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
  slack:
    secure: LIYWP1YF6DEXh4gBQ0DlaQP+kenerp7Q1AC3y/+egJYUu1g2TWmBlkcpXOcdHzrgTIUX/LYnSlhowIpsW7/YwcyLn3rOJI6SJM00DrDPRm6X1586P9DcR4XiX7MChewzbnmebx6KISt6bFtfvcd67J2cinmShwXQh2AmwvuT3Tc=
