language: scala
group: edge

# Only build non-pushes (so PRs, API requests & cron jobs) OR tags OR forks OR main branch builds
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
if: type != push OR tag IS present OR repo != playframework/playframework OR branch IN (master, 2.8.x, 2.7.x, 2.6.x)

addons:
  apt:
    packages:
      # Install xmllint used to get Akka HTTP version
      - libxml2-utils
git:
  depth: false # Avoid sbt-dynver not seeing the tag

env:
  global:
    - secure: "NS2hMbBcmi6EF4QxtcNs4A2ZuNmIdLYQRJUWWejgnD4YtcsmoVjxrHRedqrnDdui4DyvaxWhg/3Uds23jEKTSbbh3ZphLO77BVgM2nUGUvVoa4i6qGF2eZFlIhq2G1gM700GPV7X4KmyjYi2HtH8CWBTkqP3g0An63mCZw/Gnlk="
    # These are the versions used for (scripted) tests. The versions Play is build with however are defined in interplay.
    - SCRIPTED_SBT_1_3: "1.3.13"
    - SCRIPTED_SBT_1_5: "1.5.5"
    - TEST_SCALA_2_12: "2.12.14"
    - TEST_SCALA_2_13: "2.13.6"
  jobs:
    - TRAVIS_JDK=17

before_install:
  - |
    curl -Ls https://git.io/sbt -o sbt || travis_terminate 1
    chmod 0755 sbt || travis_terminate 1
    sudo mv sbt /usr/local/bin/sbt || travis_terminate 1
  - curl --version # for debug purpose
  - if [ ! -f ~/.jabba/jabba.sh ]; then curl -L -v --retry 5 -o jabba-install.sh https://git.io/jabba && bash jabba-install.sh; fi
  - . ~/.jabba/jabba.sh 
install: jabba install 1.17.0-custom=tgz+https://github.com/adoptium/temurin17-binaries/releases/download/jdk17-2021-07-09-12-54-beta/OpenJDK17-jdk_x64_linux_hotspot_2021-07-09-12-54.tar.gz && jabba use 1.17.0-custom && java -Xmx32m -version

after_script:
  - echo "(before unset) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
  - unset JAVA_TOOL_OPTIONS
  - echo "(after unset) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"

stages:
  - validations
  - test
  - test-sbt-1.3.x
  - test-sbt-1.5.x

jobs:
  include:
    - stage: validations
      name: "Run publishLocal"
      script: scripts/publish-local
      workspaces:
        create:
          name: published-local
          paths: "$HOME/.ivy2/local/com.typesafe.play"
    - script: scripts/validate-code
      name: "Code validations (format, binary compatibilty, whitesource, etc.)"
#   - script: scripts/validate-docs
#     name: "Validate docs (links, sample code, etc.)"
    - script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/validate-microbenchmarks
      name: "Validate that microbenchmarks are runnable"

    - stage: test
      script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/it-test $TEST_SCALA_2_13
      name: "Run it tests for Scala 2.13"
    - script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/it-test $TEST_SCALA_2_12
      name: "Run it tests for Scala 2.12"
    - script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/test $TEST_SCALA_2_13
      name: "Run tests for Scala 2.13"
    - script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/test $TEST_SCALA_2_12
      name: "Run tests for Scala 2.12"
    - script: scripts/test-docs $TEST_SCALA_2_13
      name: "Run documentation tests 2.13"
    - script: scripts/test-docs $TEST_SCALA_2_12
      name: "Run documentation tests 2.12"

    - stage: test-sbt-1.3.x
      name: "Run scripted tests (a) for sbt 1.3.x and Scala 2.12.x"
      script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/test-scripted $SCRIPTED_SBT_1_3 $TEST_SCALA_2_12 'play-sbt-plugin/*1of3'
      workspaces:
        use: published-local
    - name: "Run scripted tests (b) for sbt 1.3.x and Scala 2.12.x"
      script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/test-scripted $SCRIPTED_SBT_1_3 $TEST_SCALA_2_12 'play-sbt-plugin/*2of3'
      workspaces:
        use: published-local
    - name: "Run scripted tests (c) for sbt 1.3.x and Scala 2.12.x"
      script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/test-scripted $SCRIPTED_SBT_1_3 $TEST_SCALA_2_12 'play-sbt-plugin/*3of3'
      workspaces:
        use: published-local
    - name: "Run tests for sbt 1.3.x and Scala 2.13.x"
      script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/test-scripted $SCRIPTED_SBT_1_3 $TEST_SCALA_2_13
      workspaces:
        use: published-local

    # Test against sbt 1.5.x
    - stage: test-sbt-1.5.x
      name: "Run tests for 1.5.x and Scala 2.13.x"
      script:
        - echo "(before set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - if [ "$TRAVIS_JDK" = 17 ]; then export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-exports=java.base/sun.security.x509=ALL-UNNAMED"; fi
        - echo "(after set) JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
        - scripts/test-scripted $SCRIPTED_SBT_1_5 $TEST_SCALA_2_13
      workspaces:
        use: published-local

cache:
  directories:
    - "$HOME/.cache/coursier"
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba"
    - "$HOME/.sbt"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  email:
    recipients:
      secure: gxDYtOlihOtFCVxfwjoqRfOJly7EjvUB9KyP4Vz/QyaLVFOKEBQj2z64CaWwsog9g4cb7cWzjofftDhDY/8r16OnG9k3K5OTO4jzD+6N6a2bAFvTjCOrFX/GIPU0hle2Jr0Y7+t1NtkCPlcSDCQ2RyQX4izhyJoL1kOgrUQlutM=
    on_failure: always  
    on_success: never
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
  slack:
    secure: bMaBU2Az2YK0rVx95luyOikXqB/C5khfvuVI03muOGFfdiEEBEZYoqiCtB7OisveBU/orQCrjZJRL9+vCsEwVvIFF1eIa66ZE8wOTOGNMdv8hetdfR6dg2+RLrnE0zltVhlG2XMFK7X743utmE8e3koMWYH8uQSTQCXdOoUJwpQ=
    on_success: never
    on_failure: always
