language: scala

# Only build non-pushes (so PRs, API requests & cron jobs) OR tags OR forks OR main branch builds
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
if: type != push OR tag IS present OR repo != playframework/playframework OR branch IN (master, 2.7.x, 2.6.x)

addons:
  apt:
    packages:
      # Install xmllint used to get Akka HTTP version
      - libxml2-utils

env:
  global:
    - secure: "NS2hMbBcmi6EF4QxtcNs4A2ZuNmIdLYQRJUWWejgnD4YtcsmoVjxrHRedqrnDdui4DyvaxWhg/3Uds23jEKTSbbh3ZphLO77BVgM2nUGUvVoa4i6qGF2eZFlIhq2G1gM700GPV7X4KmyjYi2HtH8CWBTkqP3g0An63mCZw/Gnlk="
  matrix:
    - TRAVIS_JDK=adopt@1.8.202-08

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use $_ && java -Xmx32m -version

stages:
  - validations
  - test
  - publish-local
  - test-sbt
  - java11

jobs:
  include:
    - stage: validations
      script: scripts/validate-code
      name: "Code validations (format, binary compatibilty, whitesource, etc.)"
    - script: scripts/validate-docs
      name: "Validate docs (links, sample code, etc.)"
    - script: scripts/validate-microbenchmarks
      name: "Validate that microbenchmarks are runnable"

    - stage: test
      script: scripts/test-scala-212
      name: "Run tests for Scala 2.12"
    - script: scripts/test-docs-212
      name: "Run documentation tests 2.12"
    - script: scripts/it-test-scala-212
      name: "Run it tests for Scala 2.12"
    - script: scripts/test-scala-213
      name: "Run tests for Scala 2.13"
    - script: scripts/test-docs-213
      name: "Run documentation tests 2.13"
    - script: scripts/it-test-scala-213
      name: "Run it tests for Scala 2.13"

    - stage: publish-local
      name: "Clean ~/.ivy2/local and cross-run publishLocal"
      script: scripts/clean-and-cross-publish-local
    - name: "Clean ~/.ivy2/local and cross-run publishLocal on Java 11"
      script: scripts/clean-and-cross-publish-local
      env: TRAVIS_JDK=adopt@1.11.0-2

    - stage: test-sbt
      name: "Run scripted tests (a) for sbt 0.13.x"
      script: scripts/test-scripted 0.13.x 'play-sbt-plugin/*1of3'
    - name: "Run scripted tests (b) for sbt 0.13.x"
      script: scripts/test-scripted 0.13.x 'play-sbt-plugin/*2of3'
    - name: "Run scripted tests (c) for sbt 0.13.x"
      script: scripts/test-scripted 0.13.x 'play-sbt-plugin/*3of3'
    - name: "Run scripted tests (a) for sbt 1.x"
      script: scripts/test-scripted 1.x 'play-sbt-plugin/*1of3'
    - name: "Run scripted tests (b) for sbt 1.x"
      script: scripts/test-scripted 1.x 'play-sbt-plugin/*2of3'
    - name: "Run scripted tests (c) for sbt 1.x"
      script: scripts/test-scripted 1.x 'play-sbt-plugin/*3of3'

    # Test against Java 11, but only for Scala 2.12
    - stage: java11
      script: scripts/test-scala-212
      env: TRAVIS_JDK=adopt@1.11.0-2
      name: "Run tests for Scala 2.12 and Java 11"
    - script: scripts/it-test-scala-212
      env: TRAVIS_JDK=adopt@1.11.0-2
      name: "Run it tests for Scala 2.12 and Java 11"
    - script: scripts/test-docs-212
      env: TRAVIS_JDK=adopt@1.11.0-2
      name: "Run documentation tests for Scala 2.12 and Java 11"
    - name: "Run scripted tests (a) for sbt 1.x and Java 11"
      script: scripts/test-scripted 1.x 'play-sbt-plugin/*1of3'
      env: TRAVIS_JDK=adopt@1.11.0-2
    - name: "Run scripted tests (b) for sbt 1.x and Java 11"
      script: scripts/test-scripted 1.x 'play-sbt-plugin/*2of3'
      env: TRAVIS_JDK=adopt@1.11.0-2
    - name: "Run scripted tests (c) for sbt 1.x and Java 11"
      script: scripts/test-scripted 1.x 'play-sbt-plugin/*3of3'
      env: TRAVIS_JDK=adopt@1.11.0-2

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.ivy2/local"
    - "$HOME/.jabba/jdk"
    - "$HOME/.sbt"

before_cache: find $HOME/.sbt -name "*.lock" -delete

notifications:
  email:
    recipients:
      secure: mpliytE8tmhTD4Dn9P5Cvkc/DzLiAoaVPKo5zvMpB19VFZsAKswNrNAhnG04osyeO/Gf5JQfScCMiVP0/VUzBeZxtQmiTUScaD6N9zKDyEN81T0r1W977fkqwP9Qx1wz4sk8w90+IJbHnjhmASCsh9xNx//MYGlAOWCSXsS5FzE=
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
  slack:
    secure: bMaBU2Az2YK0rVx95luyOikXqB/C5khfvuVI03muOGFfdiEEBEZYoqiCtB7OisveBU/orQCrjZJRL9+vCsEwVvIFF1eIa66ZE8wOTOGNMdv8hetdfR6dg2+RLrnE0zltVhlG2XMFK7X743utmE8e3koMWYH8uQSTQCXdOoUJwpQ=
    on_success: never
    on_failure: always
