language: scala
dist: trusty
sudo: false
group: beta
jdk:
- oraclejdk8
env:
  matrix:
  - SCRIPT=codeChecks
  - SCRIPT=test
  - SCRIPT=testSbtPlugins
  - SCRIPT=testDocumentation
  - SCRIPT=testTemplates
  - SCRIPT=whitesource
  global:
    secure: "LJoRKoBXzuQwRThzokkYQ9nxy0unJeaqSumM0H/Ffz8YFmcRDCpoPiepwJJAn6JWauGmaCB/edAy9h9+0Emuffa+iyf4mUpVxZR27vYLOJ8hl9YIZ6xMNZETAZhdJPC7TmhNxTuRYWwYYdRkcqkPZapVmNZXcW+El5hmEYIel/Y="
script:
- framework/bin/$SCRIPT "set concurrentRestrictions in Global += Tags.limitAll(1)"
cache:
  directories:
  - $HOME/.ivy2/cache
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
