language: scala

# Only build non-pushes (so PRs, API requests & cron jobs) OR tags OR forks OR main branch builds
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
if: type != push OR tag IS present OR repo != playframework/playframework OR branch IN (master, 2.7.x, 2.6.x)

addons:
  apt:
    packages:
      # Install xmllint used to get Akka HTTP version
      - libxml2-utils
git:
  depth: false # Avoid sbt-dynver not seeing the tag

env:
  global:
    - secure: "NS2hMbBcmi6EF4QxtcNs4A2ZuNmIdLYQRJUWWejgnD4YtcsmoVjxrHRedqrnDdui4DyvaxWhg/3Uds23jEKTSbbh3ZphLO77BVgM2nUGUvVoa4i6qGF2eZFlIhq2G1gM700GPV7X4KmyjYi2HtH8CWBTkqP3g0An63mCZw/Gnlk="
    # These are the versions used for (scripted) tests. The versions Play is build with however are defined in interplay.
    - SCRIPTED_SBT_0_13: "0.13.18"
    - SCRIPTED_SBT_1_3: "1.3.13"
    - SCRIPTED_SBT_1_5: "1.5.0-RC2"
    - TEST_SCALA_2_12: "2.12.13"
    - TEST_SCALA_2_13: "2.13.5"
  jobs:
    - TRAVIS_JDK=8

before_install:
  - |
    curl -Ls https://git.io/sbt -o sbt || travis_terminate 1
    chmod 0755 sbt || travis_terminate 1
    sudo mv sbt /usr/local/bin/sbt || travis_terminate 1
  - curl --version # for debug purpose
  - if [ ! -f ~/.jabba/jabba.sh ]; then curl -L -v --retry 5 -o jabba-install.sh https://git.io/jabba && bash jabba-install.sh; fi
  - . ~/.jabba/jabba.sh 
install: jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version

stages:
  - validations
  - test
  - test-sbt-1.3.x
  - cron-test-sbt-1.3.x
  - cron-test-sbt-1.5.x
  - java11

jobs:
  include:
    - stage: validations
      name: "Run publishLocal"
      script: scripts/publish-local
      workspaces:
        create:
          name: published-local
          paths: "$HOME/.ivy2/local/com.typesafe.play"
    - name: "Run publishLocal on Java 11"
      script: scripts/publish-local
      env: TRAVIS_JDK=11
      workspaces:
        create:
          name: published-local-jdk11
          paths: "$HOME/.ivy2/local/com.typesafe.play"


    # Test against sbt 1.5.x
    - stage: cron-test-sbt-1.5.x
      name: "Run tests for 1.5.x and Scala 2.13.x"
      script: scripts/test-scripted $SCRIPTED_SBT_1_5 $TEST_SCALA_2_13
      workspaces:
        use: published-local
    - name: "Run tests for 1.5.x and Scala 2.12.x"
      script: scripts/test-scripted $SCRIPTED_SBT_1_5 $TEST_SCALA_2_12
      workspaces:
        use: published-local
    - name: "Run tests for 1.5.x and Scala 2.13.x on Java 11"
      script: scripts/test-scripted $SCRIPTED_SBT_1_5 $TEST_SCALA_2_13
      env: TRAVIS_JDK=11
      workspaces:
        use: published-local-jdk11
    - name: "Run tests for 1.5.x and Scala 2.12.x on Java 11"
      script: scripts/test-scripted $SCRIPTED_SBT_1_5 $TEST_SCALA_2_12
      env: TRAVIS_JDK=11
      workspaces:
        use: published-local-jdk11

cache:
  directories:
    - "$HOME/.cache/coursier"
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba"
    - "$HOME/.sbt"

before_cache:
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  email:
    recipients:
      secure: gxDYtOlihOtFCVxfwjoqRfOJly7EjvUB9KyP4Vz/QyaLVFOKEBQj2z64CaWwsog9g4cb7cWzjofftDhDY/8r16OnG9k3K5OTO4jzD+6N6a2bAFvTjCOrFX/GIPU0hle2Jr0Y7+t1NtkCPlcSDCQ2RyQX4izhyJoL1kOgrUQlutM=
    on_failure: always  
    on_success: never
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
  slack:
    secure: bMaBU2Az2YK0rVx95luyOikXqB/C5khfvuVI03muOGFfdiEEBEZYoqiCtB7OisveBU/orQCrjZJRL9+vCsEwVvIFF1eIa66ZE8wOTOGNMdv8hetdfR6dg2+RLrnE0zltVhlG2XMFK7X743utmE8e3koMWYH8uQSTQCXdOoUJwpQ=
    on_success: never
    on_failure: always
